export const GET_POST_PAGE_REQUEST = "GET_POST_PAGE_REQUEST";
export const GET_POST_PAGE_SUCCESS = "GET_POST_PAGE_SUCCESS";
export const GET_POST_PAGE_FAIL = "GET_POST_PAGE_FAIL";
export const POST_PAGE_CHANGE_LIKE_STATE = "POST_PAGE_CHANGE_LIKE_STATE";
export const POST_PAGE_CHANGE_COMMENT_LIKE_STATE = "POST_PAGE_CHANGE_COMMENT_LIKE_STATE";
