export const GET_POST_STREAM_REQUEST = "GET_POST_STREAM_REQUEST";
export const GET_POST_STREAM_SUCCESS = "GET_POST_STREAM_SUCCESS";
export const GET_POST_STREAM_FAIL = "GET_POST_STREAM_FAIL";
export const POST_PREVIEW_CHANGE_LIKE_STATE = "POST_PREVIEW_CHANGE_LIKE_STATE";
